language: python
os: linux
dist: trusty
sudo: false

python:
  - "3.6"
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install -r test-requirements.txt

script:
  - make
  - make lint

jobs:
  include:
    - stage: distribute
      if: branch = master AND type != pull_request
      install: make install
      script: make distribute
    - os: osx
      language: generic
      if: branch = master AND type != pull_request
      install:
        - brew upgrade python
        - sudo mkdir -p /usr/local/man
        - sudo chown -R "$USER:admin" /usr/local/man
        - make install
      script: make distribute-bin
