language: python
os: linux
dist: trusty
sudo: true # required because of SSE4.1 support
if: tag IS blank

python:
  - "3.6"
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install -r test-requirements.txt

script:
  - make test SEND_COVERAGE=true
  - make

jobs:
  include:
    - stage: distribute
      if: branch = master AND type != pull_request
      install: make install
      script: make distribute
    - os: osx
      language: generic
      if: branch = master AND type != pull_request
      install:
        - brew update && brew uninstall --ignore-dependencies --force python && brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb
        - unlink /usr/local/bin/python; ln -s /usr/local/bin/python3 /usr/local/bin/python
        - export PATH=/usr/local/bin:$PATH
        - sudo mkdir -p /usr/local/man
        - sudo chown -R "$USER:admin" /usr/local/man
        - make install
      script: make distribute
